mysql:
  image: mysql:8.0
  database: wordpress
  user: wpuser

wordpress:
  image: wordpress:latest

secrets:
  mysqlRootPassword: "rootpass123"
  mysqlPassword: "wppass123"
ingress:
  enabled: true
  hostname: myblog.local
  ingressClassName: nginx
  tls: true
  tlsSecret: wordpress-tls
