mysql:
  image: mysql:8.0
  database: wordpress
  user: wpuser

wordpress:
  image: wordpress:latest

secrets:
  mysqlRootPassword: "******"
  mysqlPassword: "********"
ingress:
  enabled: true
  hostname: myblog.local
  ingressClassName: nginx
  tls: true
  tlsSecret: wordpress-tls
